/*
 * Dynatrace Environment API
 *
 *  Documentation of the Dynatrace Environment API v2. Resources here generally supersede those in v1. Migration of resources from v1 is in progress.   If you miss a resource, consider using the Dynatrace Environment API v1. To read about use cases and examples, see [Dynatrace Documentation](https://dt-url.net/2u23k1k) .  Notes about compatibility: * Operations marked as early adopter or preview may be changed in non-compatible ways, although we try to avoid this. * We may add new enum constants without incrementing the API version; thus, clients need to handle unknown enum constants gracefully.
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dynatrace

import (
	"encoding/json"
)

// ExtensionEventsList struct for ExtensionEventsList
type ExtensionEventsList struct {
	// A list of extension events.
	ExtensionEvents *[]ExtensionEventDto `json:"extensionEvents,omitempty"`
}

// NewExtensionEventsList instantiates a new ExtensionEventsList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExtensionEventsList() *ExtensionEventsList {
	this := ExtensionEventsList{}
	return &this
}

// NewExtensionEventsListWithDefaults instantiates a new ExtensionEventsList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExtensionEventsListWithDefaults() *ExtensionEventsList {
	this := ExtensionEventsList{}
	return &this
}

// GetExtensionEvents returns the ExtensionEvents field value if set, zero value otherwise.
func (o *ExtensionEventsList) GetExtensionEvents() []ExtensionEventDto {
	if o == nil || o.ExtensionEvents == nil {
		var ret []ExtensionEventDto
		return ret
	}
	return *o.ExtensionEvents
}

// GetExtensionEventsOk returns a tuple with the ExtensionEvents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExtensionEventsList) GetExtensionEventsOk() (*[]ExtensionEventDto, bool) {
	if o == nil || o.ExtensionEvents == nil {
		return nil, false
	}
	return o.ExtensionEvents, true
}

// HasExtensionEvents returns a boolean if a field has been set.
func (o *ExtensionEventsList) HasExtensionEvents() bool {
	if o != nil && o.ExtensionEvents != nil {
		return true
	}

	return false
}

// SetExtensionEvents gets a reference to the given []ExtensionEventDto and assigns it to the ExtensionEvents field.
func (o *ExtensionEventsList) SetExtensionEvents(v []ExtensionEventDto) {
	o.ExtensionEvents = &v
}

func (o ExtensionEventsList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ExtensionEvents != nil {
		toSerialize["extensionEvents"] = o.ExtensionEvents
	}
	return json.Marshal(toSerialize)
}

type NullableExtensionEventsList struct {
	value *ExtensionEventsList
	isSet bool
}

func (v NullableExtensionEventsList) Get() *ExtensionEventsList {
	return v.value
}

func (v *NullableExtensionEventsList) Set(val *ExtensionEventsList) {
	v.value = val
	v.isSet = true
}

func (v NullableExtensionEventsList) IsSet() bool {
	return v.isSet
}

func (v *NullableExtensionEventsList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExtensionEventsList(val *ExtensionEventsList) *NullableExtensionEventsList {
	return &NullableExtensionEventsList{value: val, isSet: true}
}

func (v NullableExtensionEventsList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExtensionEventsList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


