/*
 * Dynatrace Cluster API
 *
 * Dynatrace Managed exposes cluster-wide functionality via REST endpoints. This interactive documentation also acts as a REST client you can use to interact with Dynatrace Managed clusters.   To authorize, use the API Token generated in [Settings - API Tokens page](/cmc#cm/apiToken). The HTTP status code of the response shows the result of your request. The expected response code for a successful request is documented individually per REST endpoint. Additionally the following error response codes can occur in our REST interface:  * 400 - Bad Request: Some request parameters are not correct. See response body for details. * 401 - Unauthorized: A valid authorization header is required but is missing. * 403 - Forbidden: Execution of request is not allowed, e.g. api-token is invalid. * 404 - Not Found: Endpoint does not exist or some entities could not be found. * 500 - Internal Server Error: See response body for details. * 556 - Upgrade in progress: Operation couldn't be performed during the upgrade.  Notes about compatibility: * Operations marked as early adopter or preview may be changed in non-compatible ways, although we try to avoid this. * We may add new enum constants without incrementing the API version; thus, clients need to handle unknown enum constants gracefully.
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dynatrace

import (
	"encoding/json"
)

// NetworkZone Configuration of a network zone.
type NetworkZone struct {
	// The number of ActiveGates in the network zone.
	NumOfConfiguredActiveGates *int32 `json:"numOfConfiguredActiveGates,omitempty"`
	// A list of alternative network zones.
	AlternativeZones *[]string `json:"alternativeZones,omitempty"`
	// The number of OneAgents that are using ActiveGates in the network zone.
	NumOfOneAgentsUsing *int32 `json:"numOfOneAgentsUsing,omitempty"`
	// The number of OneAgents that are configured to use the network zone as primary.
	NumOfConfiguredOneAgents *int32 `json:"numOfConfiguredOneAgents,omitempty"`
	// The number of OneAgents from other network zones that are using ActiveGates in the network zone.    This is a fraction of **numOfOneAgentsUsing**.   One possible reason for switching to another zone is that a firewall is preventing a OneAgent from connecting to any ActiveGate in the preferred network zone.  
	NumOfOneAgentsFromOtherZones *int32 `json:"numOfOneAgentsFromOtherZones,omitempty"`
	// A short description of the network zone
	Description *string `json:"description,omitempty"`
	// The ID of the network zone
	Id *string `json:"id,omitempty"`
}

// NewNetworkZone instantiates a new NetworkZone object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkZone() *NetworkZone {
	this := NetworkZone{}
	return &this
}

// NewNetworkZoneWithDefaults instantiates a new NetworkZone object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkZoneWithDefaults() *NetworkZone {
	this := NetworkZone{}
	return &this
}

// GetNumOfConfiguredActiveGates returns the NumOfConfiguredActiveGates field value if set, zero value otherwise.
func (o *NetworkZone) GetNumOfConfiguredActiveGates() int32 {
	if o == nil || o.NumOfConfiguredActiveGates == nil {
		var ret int32
		return ret
	}
	return *o.NumOfConfiguredActiveGates
}

// GetNumOfConfiguredActiveGatesOk returns a tuple with the NumOfConfiguredActiveGates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkZone) GetNumOfConfiguredActiveGatesOk() (*int32, bool) {
	if o == nil || o.NumOfConfiguredActiveGates == nil {
		return nil, false
	}
	return o.NumOfConfiguredActiveGates, true
}

// HasNumOfConfiguredActiveGates returns a boolean if a field has been set.
func (o *NetworkZone) HasNumOfConfiguredActiveGates() bool {
	if o != nil && o.NumOfConfiguredActiveGates != nil {
		return true
	}

	return false
}

// SetNumOfConfiguredActiveGates gets a reference to the given int32 and assigns it to the NumOfConfiguredActiveGates field.
func (o *NetworkZone) SetNumOfConfiguredActiveGates(v int32) {
	o.NumOfConfiguredActiveGates = &v
}

// GetAlternativeZones returns the AlternativeZones field value if set, zero value otherwise.
func (o *NetworkZone) GetAlternativeZones() []string {
	if o == nil || o.AlternativeZones == nil {
		var ret []string
		return ret
	}
	return *o.AlternativeZones
}

// GetAlternativeZonesOk returns a tuple with the AlternativeZones field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkZone) GetAlternativeZonesOk() (*[]string, bool) {
	if o == nil || o.AlternativeZones == nil {
		return nil, false
	}
	return o.AlternativeZones, true
}

// HasAlternativeZones returns a boolean if a field has been set.
func (o *NetworkZone) HasAlternativeZones() bool {
	if o != nil && o.AlternativeZones != nil {
		return true
	}

	return false
}

// SetAlternativeZones gets a reference to the given []string and assigns it to the AlternativeZones field.
func (o *NetworkZone) SetAlternativeZones(v []string) {
	o.AlternativeZones = &v
}

// GetNumOfOneAgentsUsing returns the NumOfOneAgentsUsing field value if set, zero value otherwise.
func (o *NetworkZone) GetNumOfOneAgentsUsing() int32 {
	if o == nil || o.NumOfOneAgentsUsing == nil {
		var ret int32
		return ret
	}
	return *o.NumOfOneAgentsUsing
}

// GetNumOfOneAgentsUsingOk returns a tuple with the NumOfOneAgentsUsing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkZone) GetNumOfOneAgentsUsingOk() (*int32, bool) {
	if o == nil || o.NumOfOneAgentsUsing == nil {
		return nil, false
	}
	return o.NumOfOneAgentsUsing, true
}

// HasNumOfOneAgentsUsing returns a boolean if a field has been set.
func (o *NetworkZone) HasNumOfOneAgentsUsing() bool {
	if o != nil && o.NumOfOneAgentsUsing != nil {
		return true
	}

	return false
}

// SetNumOfOneAgentsUsing gets a reference to the given int32 and assigns it to the NumOfOneAgentsUsing field.
func (o *NetworkZone) SetNumOfOneAgentsUsing(v int32) {
	o.NumOfOneAgentsUsing = &v
}

// GetNumOfConfiguredOneAgents returns the NumOfConfiguredOneAgents field value if set, zero value otherwise.
func (o *NetworkZone) GetNumOfConfiguredOneAgents() int32 {
	if o == nil || o.NumOfConfiguredOneAgents == nil {
		var ret int32
		return ret
	}
	return *o.NumOfConfiguredOneAgents
}

// GetNumOfConfiguredOneAgentsOk returns a tuple with the NumOfConfiguredOneAgents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkZone) GetNumOfConfiguredOneAgentsOk() (*int32, bool) {
	if o == nil || o.NumOfConfiguredOneAgents == nil {
		return nil, false
	}
	return o.NumOfConfiguredOneAgents, true
}

// HasNumOfConfiguredOneAgents returns a boolean if a field has been set.
func (o *NetworkZone) HasNumOfConfiguredOneAgents() bool {
	if o != nil && o.NumOfConfiguredOneAgents != nil {
		return true
	}

	return false
}

// SetNumOfConfiguredOneAgents gets a reference to the given int32 and assigns it to the NumOfConfiguredOneAgents field.
func (o *NetworkZone) SetNumOfConfiguredOneAgents(v int32) {
	o.NumOfConfiguredOneAgents = &v
}

// GetNumOfOneAgentsFromOtherZones returns the NumOfOneAgentsFromOtherZones field value if set, zero value otherwise.
func (o *NetworkZone) GetNumOfOneAgentsFromOtherZones() int32 {
	if o == nil || o.NumOfOneAgentsFromOtherZones == nil {
		var ret int32
		return ret
	}
	return *o.NumOfOneAgentsFromOtherZones
}

// GetNumOfOneAgentsFromOtherZonesOk returns a tuple with the NumOfOneAgentsFromOtherZones field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkZone) GetNumOfOneAgentsFromOtherZonesOk() (*int32, bool) {
	if o == nil || o.NumOfOneAgentsFromOtherZones == nil {
		return nil, false
	}
	return o.NumOfOneAgentsFromOtherZones, true
}

// HasNumOfOneAgentsFromOtherZones returns a boolean if a field has been set.
func (o *NetworkZone) HasNumOfOneAgentsFromOtherZones() bool {
	if o != nil && o.NumOfOneAgentsFromOtherZones != nil {
		return true
	}

	return false
}

// SetNumOfOneAgentsFromOtherZones gets a reference to the given int32 and assigns it to the NumOfOneAgentsFromOtherZones field.
func (o *NetworkZone) SetNumOfOneAgentsFromOtherZones(v int32) {
	o.NumOfOneAgentsFromOtherZones = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *NetworkZone) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkZone) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *NetworkZone) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *NetworkZone) SetDescription(v string) {
	o.Description = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *NetworkZone) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkZone) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *NetworkZone) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *NetworkZone) SetId(v string) {
	o.Id = &v
}

func (o NetworkZone) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.NumOfConfiguredActiveGates != nil {
		toSerialize["numOfConfiguredActiveGates"] = o.NumOfConfiguredActiveGates
	}
	if o.AlternativeZones != nil {
		toSerialize["alternativeZones"] = o.AlternativeZones
	}
	if o.NumOfOneAgentsUsing != nil {
		toSerialize["numOfOneAgentsUsing"] = o.NumOfOneAgentsUsing
	}
	if o.NumOfConfiguredOneAgents != nil {
		toSerialize["numOfConfiguredOneAgents"] = o.NumOfConfiguredOneAgents
	}
	if o.NumOfOneAgentsFromOtherZones != nil {
		toSerialize["numOfOneAgentsFromOtherZones"] = o.NumOfOneAgentsFromOtherZones
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableNetworkZone struct {
	value *NetworkZone
	isSet bool
}

func (v NullableNetworkZone) Get() *NetworkZone {
	return v.value
}

func (v *NullableNetworkZone) Set(val *NetworkZone) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkZone) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkZone) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkZone(val *NetworkZone) *NullableNetworkZone {
	return &NullableNetworkZone{value: val, isSet: true}
}

func (v NullableNetworkZone) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkZone) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


