/*
 * Dynatrace Configuration API
 *
 * Documentation of the Dynatrace Configuration API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/config-api) to read about use-cases and examples.  Notes about compatibility: * Operations marked as early adopter or preview may be changed in non-compatible ways, although we try to avoid this. * We may add new enum constants without incrementing the API version; thus, clients need to handle unknown enum constants gracefully.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dynatrace
// AwsCredentialsConfig Configuration of an AWS credentials.
type AwsCredentialsConfig struct {
	Metadata ConfigurationMetadata `json:"metadata,omitempty"`
	// The unique ID of the credentials.
	Id string `json:"id,omitempty"`
	// The status of the connection to the AWS environment.    * `CONNECTED`: There was a connection within last 10 minutes.  * `DISCONNECTED`: A problem occurred with establishing connection using these credentials. Check whether the data is correct.  * `UNINITIALIZED`: The successful connection has never been established for these credentials.
	ConnectionStatus string `json:"connectionStatus,omitempty"`
	// The name of the credentials.
	Label string `json:"label"`
	// The type of the AWS partition.
	PartitionType string `json:"partitionType"`
	AuthenticationData AwsAuthenticationData `json:"authenticationData"`
	// Monitor only resources which have specified AWS tags (`true`) or all resources (`false`).
	TaggedOnly bool `json:"taggedOnly"`
	// A list of AWS tags to be monitored.   You can specify up to 10 tags.   Only applicable when the **taggedOnly** parameter is set to `true`.
	TagsToMonitor []AwsConfigTag `json:"tagsToMonitor"`
	// A list of supporting services to be monitored.
	SupportingServicesToMonitor []AwsSupportingServiceConfig `json:"supportingServicesToMonitor,omitempty"`
}
