/*
 * Dynatrace Configuration API
 *
 * Documentation of the Dynatrace Configuration API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/config-api) to read about use-cases and examples.  Notes about compatibility: * Operations marked as early adopter or preview may be changed in non-compatible ways, although we try to avoid this. * We may add new enum constants without incrementing the API version; thus, clients need to handle unknown enum constants gracefully.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dynatrace
// EsxiHighCpuThresholds Custom thresholds for CPU saturation detection on ESXi. If not set then the automatic mode is used.    **All** conditions must be fulfilled to trigger an alert.
type EsxiHighCpuThresholds struct {
	// CPU usage is higher than *X*% in 3 out of 5 samples.
	CpuUsagePercentage int32 `json:"cpuUsagePercentage"`
	// VM CPU ready is higher than *X*% in 3 out of 5 samples.
	VmCpuReadyPercentage int32 `json:"vmCpuReadyPercentage"`
	// At least one peak higher than *X*% occurred in 3 out of 5 samples.
	CpuPeakPercentage int32 `json:"cpuPeakPercentage"`
}
