/*
 * Dynatrace Configuration API
 *
 * Documentation of the Dynatrace Configuration API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/config-api) to read about use-cases and examples.  Notes about compatibility: * Operations marked as early adopter or preview may be changed in non-compatible ways, although we try to avoid this. * We may add new enum constants without incrementing the API version; thus, clients need to handle unknown enum constants gracefully.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dynatrace
// UserPasswordCredentialsAllOf struct for UserPasswordCredentialsAllOf
type UserPasswordCredentialsAllOf struct {
	// The username of the credentials set.
	User string `json:"user,omitempty"`
	// The password of the credential.
	Password string `json:"password,omitempty"`
}
