/*
 * Dynatrace Configuration API
 *
 * Documentation of the Dynatrace Configuration API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/config-api) to read about use-cases and examples.  Notes about compatibility: * Operations marked as early adopter or preview may be changed in non-compatible ways, although we try to avoid this. * We may add new enum constants without incrementing the API version; thus, clients need to handle unknown enum constants gracefully.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dynatrace

import (
	"encoding/json"
)

// ElbHighConnectionErrorsDetectionConfig The configuration of the high number of backend connection errors on ELB detection.
type ElbHighConnectionErrorsDetectionConfig struct {
	// The detection is enabled (`true`) or disabled (`false`).
	Enabled bool `json:"enabled"`
	CustomThresholds *ElbHighConnectionErrorsThresholds `json:"customThresholds,omitempty"`
}

// NewElbHighConnectionErrorsDetectionConfig instantiates a new ElbHighConnectionErrorsDetectionConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewElbHighConnectionErrorsDetectionConfig(enabled bool, ) *ElbHighConnectionErrorsDetectionConfig {
	this := ElbHighConnectionErrorsDetectionConfig{}
	this.Enabled = enabled
	return &this
}

// NewElbHighConnectionErrorsDetectionConfigWithDefaults instantiates a new ElbHighConnectionErrorsDetectionConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewElbHighConnectionErrorsDetectionConfigWithDefaults() *ElbHighConnectionErrorsDetectionConfig {
	this := ElbHighConnectionErrorsDetectionConfig{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *ElbHighConnectionErrorsDetectionConfig) GetEnabled() bool {
	if o == nil  {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *ElbHighConnectionErrorsDetectionConfig) GetEnabledOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *ElbHighConnectionErrorsDetectionConfig) SetEnabled(v bool) {
	o.Enabled = v
}

// GetCustomThresholds returns the CustomThresholds field value if set, zero value otherwise.
func (o *ElbHighConnectionErrorsDetectionConfig) GetCustomThresholds() ElbHighConnectionErrorsThresholds {
	if o == nil || o.CustomThresholds == nil {
		var ret ElbHighConnectionErrorsThresholds
		return ret
	}
	return *o.CustomThresholds
}

// GetCustomThresholdsOk returns a tuple with the CustomThresholds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ElbHighConnectionErrorsDetectionConfig) GetCustomThresholdsOk() (*ElbHighConnectionErrorsThresholds, bool) {
	if o == nil || o.CustomThresholds == nil {
		return nil, false
	}
	return o.CustomThresholds, true
}

// HasCustomThresholds returns a boolean if a field has been set.
func (o *ElbHighConnectionErrorsDetectionConfig) HasCustomThresholds() bool {
	if o != nil && o.CustomThresholds != nil {
		return true
	}

	return false
}

// SetCustomThresholds gets a reference to the given ElbHighConnectionErrorsThresholds and assigns it to the CustomThresholds field.
func (o *ElbHighConnectionErrorsDetectionConfig) SetCustomThresholds(v ElbHighConnectionErrorsThresholds) {
	o.CustomThresholds = &v
}

func (o ElbHighConnectionErrorsDetectionConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["enabled"] = o.Enabled
	}
	if o.CustomThresholds != nil {
		toSerialize["customThresholds"] = o.CustomThresholds
	}
	return json.Marshal(toSerialize)
}

type NullableElbHighConnectionErrorsDetectionConfig struct {
	value *ElbHighConnectionErrorsDetectionConfig
	isSet bool
}

func (v NullableElbHighConnectionErrorsDetectionConfig) Get() *ElbHighConnectionErrorsDetectionConfig {
	return v.value
}

func (v *NullableElbHighConnectionErrorsDetectionConfig) Set(val *ElbHighConnectionErrorsDetectionConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableElbHighConnectionErrorsDetectionConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableElbHighConnectionErrorsDetectionConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableElbHighConnectionErrorsDetectionConfig(val *ElbHighConnectionErrorsDetectionConfig) *NullableElbHighConnectionErrorsDetectionConfig {
	return &NullableElbHighConnectionErrorsDetectionConfig{value: val, isSet: true}
}

func (v NullableElbHighConnectionErrorsDetectionConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableElbHighConnectionErrorsDetectionConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


