/*
 * Dynatrace Configuration API
 *
 * Documentation of the Dynatrace Configuration API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/config-api) to read about use-cases and examples.  Notes about compatibility: * Operations marked as early adopter or preview may be changed in non-compatible ways, although we try to avoid this. * We may add new enum constants without incrementing the API version; thus, clients need to handle unknown enum constants gracefully.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dynatrace
// IpAddressRange Ip address range that can be specified as single ip address, addresses (from) and address to or address and subnet mask.
type IpAddressRange struct {
	// The subnet of the ip address range settings
	SubnetMask int32 `json:"subnetMask,omitempty"`
	// The ip address
	Address string `json:"address"`
	// The ip address to
	AddressTo string `json:"addressTo,omitempty"`
}
