/*
 * Dynatrace Configuration API
 *
 * Documentation of the Dynatrace Configuration API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/config-api) to read about use-cases and examples.  Notes about compatibility: * Operations marked as early adopter or preview may be changed in non-compatible ways, although we try to avoid this. * We may add new enum constants without incrementing the API version; thus, clients need to handle unknown enum constants gracefully.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dynatrace

import (
	"encoding/json"
)

// SymbolFile struct for SymbolFile
type SymbolFile struct {
	// The name of the application this file belongs to
	ApplicationName *string `json:"applicationName,omitempty"`
	// The size of the file in KB
	Size *int32 `json:"size,omitempty"`
	AppId *AppIdentifier `json:"appId,omitempty"`
	// The timestamp of the upload time of the file, in UTC milliseconds
	UploadTimestamp *int64 `json:"uploadTimestamp,omitempty"`
	// Is the file pinned and therefore cannot be deleted.
	Pinned *bool `json:"pinned,omitempty"`
}

// NewSymbolFile instantiates a new SymbolFile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSymbolFile() *SymbolFile {
	this := SymbolFile{}
	return &this
}

// NewSymbolFileWithDefaults instantiates a new SymbolFile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSymbolFileWithDefaults() *SymbolFile {
	this := SymbolFile{}
	return &this
}

// GetApplicationName returns the ApplicationName field value if set, zero value otherwise.
func (o *SymbolFile) GetApplicationName() string {
	if o == nil || o.ApplicationName == nil {
		var ret string
		return ret
	}
	return *o.ApplicationName
}

// GetApplicationNameOk returns a tuple with the ApplicationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SymbolFile) GetApplicationNameOk() (*string, bool) {
	if o == nil || o.ApplicationName == nil {
		return nil, false
	}
	return o.ApplicationName, true
}

// HasApplicationName returns a boolean if a field has been set.
func (o *SymbolFile) HasApplicationName() bool {
	if o != nil && o.ApplicationName != nil {
		return true
	}

	return false
}

// SetApplicationName gets a reference to the given string and assigns it to the ApplicationName field.
func (o *SymbolFile) SetApplicationName(v string) {
	o.ApplicationName = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *SymbolFile) GetSize() int32 {
	if o == nil || o.Size == nil {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SymbolFile) GetSizeOk() (*int32, bool) {
	if o == nil || o.Size == nil {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *SymbolFile) HasSize() bool {
	if o != nil && o.Size != nil {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *SymbolFile) SetSize(v int32) {
	o.Size = &v
}

// GetAppId returns the AppId field value if set, zero value otherwise.
func (o *SymbolFile) GetAppId() AppIdentifier {
	if o == nil || o.AppId == nil {
		var ret AppIdentifier
		return ret
	}
	return *o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SymbolFile) GetAppIdOk() (*AppIdentifier, bool) {
	if o == nil || o.AppId == nil {
		return nil, false
	}
	return o.AppId, true
}

// HasAppId returns a boolean if a field has been set.
func (o *SymbolFile) HasAppId() bool {
	if o != nil && o.AppId != nil {
		return true
	}

	return false
}

// SetAppId gets a reference to the given AppIdentifier and assigns it to the AppId field.
func (o *SymbolFile) SetAppId(v AppIdentifier) {
	o.AppId = &v
}

// GetUploadTimestamp returns the UploadTimestamp field value if set, zero value otherwise.
func (o *SymbolFile) GetUploadTimestamp() int64 {
	if o == nil || o.UploadTimestamp == nil {
		var ret int64
		return ret
	}
	return *o.UploadTimestamp
}

// GetUploadTimestampOk returns a tuple with the UploadTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SymbolFile) GetUploadTimestampOk() (*int64, bool) {
	if o == nil || o.UploadTimestamp == nil {
		return nil, false
	}
	return o.UploadTimestamp, true
}

// HasUploadTimestamp returns a boolean if a field has been set.
func (o *SymbolFile) HasUploadTimestamp() bool {
	if o != nil && o.UploadTimestamp != nil {
		return true
	}

	return false
}

// SetUploadTimestamp gets a reference to the given int64 and assigns it to the UploadTimestamp field.
func (o *SymbolFile) SetUploadTimestamp(v int64) {
	o.UploadTimestamp = &v
}

// GetPinned returns the Pinned field value if set, zero value otherwise.
func (o *SymbolFile) GetPinned() bool {
	if o == nil || o.Pinned == nil {
		var ret bool
		return ret
	}
	return *o.Pinned
}

// GetPinnedOk returns a tuple with the Pinned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SymbolFile) GetPinnedOk() (*bool, bool) {
	if o == nil || o.Pinned == nil {
		return nil, false
	}
	return o.Pinned, true
}

// HasPinned returns a boolean if a field has been set.
func (o *SymbolFile) HasPinned() bool {
	if o != nil && o.Pinned != nil {
		return true
	}

	return false
}

// SetPinned gets a reference to the given bool and assigns it to the Pinned field.
func (o *SymbolFile) SetPinned(v bool) {
	o.Pinned = &v
}

func (o SymbolFile) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ApplicationName != nil {
		toSerialize["applicationName"] = o.ApplicationName
	}
	if o.Size != nil {
		toSerialize["size"] = o.Size
	}
	if o.AppId != nil {
		toSerialize["appId"] = o.AppId
	}
	if o.UploadTimestamp != nil {
		toSerialize["uploadTimestamp"] = o.UploadTimestamp
	}
	if o.Pinned != nil {
		toSerialize["pinned"] = o.Pinned
	}
	return json.Marshal(toSerialize)
}

type NullableSymbolFile struct {
	value *SymbolFile
	isSet bool
}

func (v NullableSymbolFile) Get() *SymbolFile {
	return v.value
}

func (v *NullableSymbolFile) Set(val *SymbolFile) {
	v.value = val
	v.isSet = true
}

func (v NullableSymbolFile) IsSet() bool {
	return v.isSet
}

func (v *NullableSymbolFile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSymbolFile(val *SymbolFile) *NullableSymbolFile {
	return &NullableSymbolFile{value: val, isSet: true}
}

func (v NullableSymbolFile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSymbolFile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


