/*
 * Dynatrace Configuration API
 *
 * Documentation of the Dynatrace Configuration API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/config-api) to read about use-cases and examples.  Notes about compatibility: * Operations marked as early adopter or preview may be changed in non-compatible ways, although we try to avoid this. * We may add new enum constants without incrementing the API version; thus, clients need to handle unknown enum constants gracefully.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dynatrace

import (
	"encoding/json"
)

// ResourceTimingSettings Settings for resource timings capture.
type ResourceTimingSettings struct {
	// W3C resource timings for third party/CDN enabled/disabled.
	W3cResourceTimings bool `json:"w3cResourceTimings"`
	// Timing for JavaScript files and images on non-W3C supported browsers enabled/disabled.
	NonW3cResourceTimings bool `json:"nonW3cResourceTimings"`
	// Instrumentation delay for monitoring resource and image resource impact in browsers that don't offer W3C resource timings.   Valid values range from 0 to 9999.  Only effective if **nonW3cResourceTimings** is enabled.
	NonW3cResourceTimingsInstrumentationDelay int32 `json:"nonW3cResourceTimingsInstrumentationDelay"`
	// Defines how detailed resource timings are captured.  Only effective if **w3cResourceTimings** or **nonW3cResourceTimings** is enabled.
	ResourceTimingCaptureType string `json:"resourceTimingCaptureType"`
	// Limits the number of domains for which W3C resource timings are captured.  Only effective if **resourceTimingCaptureType** is `CAPTURE_LIMITED_SUMMARIES`.
	ResourceTimingsDomainLimit int32 `json:"resourceTimingsDomainLimit"`
}

// NewResourceTimingSettings instantiates a new ResourceTimingSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceTimingSettings(w3cResourceTimings bool, nonW3cResourceTimings bool, nonW3cResourceTimingsInstrumentationDelay int32, resourceTimingCaptureType string, resourceTimingsDomainLimit int32, ) *ResourceTimingSettings {
	this := ResourceTimingSettings{}
	this.W3cResourceTimings = w3cResourceTimings
	this.NonW3cResourceTimings = nonW3cResourceTimings
	this.NonW3cResourceTimingsInstrumentationDelay = nonW3cResourceTimingsInstrumentationDelay
	this.ResourceTimingCaptureType = resourceTimingCaptureType
	this.ResourceTimingsDomainLimit = resourceTimingsDomainLimit
	return &this
}

// NewResourceTimingSettingsWithDefaults instantiates a new ResourceTimingSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceTimingSettingsWithDefaults() *ResourceTimingSettings {
	this := ResourceTimingSettings{}
	return &this
}

// GetW3cResourceTimings returns the W3cResourceTimings field value
func (o *ResourceTimingSettings) GetW3cResourceTimings() bool {
	if o == nil  {
		var ret bool
		return ret
	}

	return o.W3cResourceTimings
}

// GetW3cResourceTimingsOk returns a tuple with the W3cResourceTimings field value
// and a boolean to check if the value has been set.
func (o *ResourceTimingSettings) GetW3cResourceTimingsOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.W3cResourceTimings, true
}

// SetW3cResourceTimings sets field value
func (o *ResourceTimingSettings) SetW3cResourceTimings(v bool) {
	o.W3cResourceTimings = v
}

// GetNonW3cResourceTimings returns the NonW3cResourceTimings field value
func (o *ResourceTimingSettings) GetNonW3cResourceTimings() bool {
	if o == nil  {
		var ret bool
		return ret
	}

	return o.NonW3cResourceTimings
}

// GetNonW3cResourceTimingsOk returns a tuple with the NonW3cResourceTimings field value
// and a boolean to check if the value has been set.
func (o *ResourceTimingSettings) GetNonW3cResourceTimingsOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NonW3cResourceTimings, true
}

// SetNonW3cResourceTimings sets field value
func (o *ResourceTimingSettings) SetNonW3cResourceTimings(v bool) {
	o.NonW3cResourceTimings = v
}

// GetNonW3cResourceTimingsInstrumentationDelay returns the NonW3cResourceTimingsInstrumentationDelay field value
func (o *ResourceTimingSettings) GetNonW3cResourceTimingsInstrumentationDelay() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.NonW3cResourceTimingsInstrumentationDelay
}

// GetNonW3cResourceTimingsInstrumentationDelayOk returns a tuple with the NonW3cResourceTimingsInstrumentationDelay field value
// and a boolean to check if the value has been set.
func (o *ResourceTimingSettings) GetNonW3cResourceTimingsInstrumentationDelayOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NonW3cResourceTimingsInstrumentationDelay, true
}

// SetNonW3cResourceTimingsInstrumentationDelay sets field value
func (o *ResourceTimingSettings) SetNonW3cResourceTimingsInstrumentationDelay(v int32) {
	o.NonW3cResourceTimingsInstrumentationDelay = v
}

// GetResourceTimingCaptureType returns the ResourceTimingCaptureType field value
func (o *ResourceTimingSettings) GetResourceTimingCaptureType() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.ResourceTimingCaptureType
}

// GetResourceTimingCaptureTypeOk returns a tuple with the ResourceTimingCaptureType field value
// and a boolean to check if the value has been set.
func (o *ResourceTimingSettings) GetResourceTimingCaptureTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ResourceTimingCaptureType, true
}

// SetResourceTimingCaptureType sets field value
func (o *ResourceTimingSettings) SetResourceTimingCaptureType(v string) {
	o.ResourceTimingCaptureType = v
}

// GetResourceTimingsDomainLimit returns the ResourceTimingsDomainLimit field value
func (o *ResourceTimingSettings) GetResourceTimingsDomainLimit() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.ResourceTimingsDomainLimit
}

// GetResourceTimingsDomainLimitOk returns a tuple with the ResourceTimingsDomainLimit field value
// and a boolean to check if the value has been set.
func (o *ResourceTimingSettings) GetResourceTimingsDomainLimitOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ResourceTimingsDomainLimit, true
}

// SetResourceTimingsDomainLimit sets field value
func (o *ResourceTimingSettings) SetResourceTimingsDomainLimit(v int32) {
	o.ResourceTimingsDomainLimit = v
}

func (o ResourceTimingSettings) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["w3cResourceTimings"] = o.W3cResourceTimings
	}
	if true {
		toSerialize["nonW3cResourceTimings"] = o.NonW3cResourceTimings
	}
	if true {
		toSerialize["nonW3cResourceTimingsInstrumentationDelay"] = o.NonW3cResourceTimingsInstrumentationDelay
	}
	if true {
		toSerialize["resourceTimingCaptureType"] = o.ResourceTimingCaptureType
	}
	if true {
		toSerialize["resourceTimingsDomainLimit"] = o.ResourceTimingsDomainLimit
	}
	return json.Marshal(toSerialize)
}

type NullableResourceTimingSettings struct {
	value *ResourceTimingSettings
	isSet bool
}

func (v NullableResourceTimingSettings) Get() *ResourceTimingSettings {
	return v.value
}

func (v *NullableResourceTimingSettings) Set(val *ResourceTimingSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceTimingSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceTimingSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceTimingSettings(val *ResourceTimingSettings) *NullableResourceTimingSettings {
	return &NullableResourceTimingSettings{value: val, isSet: true}
}

func (v NullableResourceTimingSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceTimingSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


