/*
 * Dynatrace Configuration API
 *
 * Documentation of the Dynatrace Configuration API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/config-api) to read about use-cases and examples.  Notes about compatibility: * Operations marked as early adopter or preview may be changed in non-compatible ways, although we try to avoid this. * We may add new enum constants without incrementing the API version; thus, clients need to handle unknown enum constants gracefully.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dynatrace
// ConversionGoal A conversion goal of the application.
type ConversionGoal struct {
	// The name of the conversion goal.
	Name string `json:"name"`
	// The ID of conversion goal.    Omit it while creating a new conversion goal.
	Id string `json:"id,omitempty"`
	// The type of the conversion goal.
	Type string `json:"type,omitempty"`
	DestinationDetails DestinationDetails `json:"destinationDetails,omitempty"`
	UserActionDetails UserActionDetails `json:"userActionDetails,omitempty"`
	VisitDurationDetails VisitDurationDetails `json:"visitDurationDetails,omitempty"`
	VisitNumActionDetails VisitNumActionDetails `json:"visitNumActionDetails,omitempty"`
}
