/*
 * Dynatrace Configuration API
 *
 * Documentation of the Dynatrace Configuration API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/config-api) to read about use-cases and examples.  Notes about compatibility: * Operations marked as early adopter or preview may be changed in non-compatible ways, although we try to avoid this. * We may add new enum constants without incrementing the API version; thus, clients need to handle unknown enum constants gracefully.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dynatrace

import (
	"encoding/json"
)

// OutOfMemoryThresholds Custom thresholds for Java out of memory. If not set, automatic mode is used.
type OutOfMemoryThresholds struct {
	// Alert if the number of Java out of memory exceptions is *X* per minute or higher.
	OutOfMemoryExceptionsNumber int32 `json:"outOfMemoryExceptionsNumber"`
}

// NewOutOfMemoryThresholds instantiates a new OutOfMemoryThresholds object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutOfMemoryThresholds(outOfMemoryExceptionsNumber int32, ) *OutOfMemoryThresholds {
	this := OutOfMemoryThresholds{}
	this.OutOfMemoryExceptionsNumber = outOfMemoryExceptionsNumber
	return &this
}

// NewOutOfMemoryThresholdsWithDefaults instantiates a new OutOfMemoryThresholds object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutOfMemoryThresholdsWithDefaults() *OutOfMemoryThresholds {
	this := OutOfMemoryThresholds{}
	return &this
}

// GetOutOfMemoryExceptionsNumber returns the OutOfMemoryExceptionsNumber field value
func (o *OutOfMemoryThresholds) GetOutOfMemoryExceptionsNumber() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.OutOfMemoryExceptionsNumber
}

// GetOutOfMemoryExceptionsNumberOk returns a tuple with the OutOfMemoryExceptionsNumber field value
// and a boolean to check if the value has been set.
func (o *OutOfMemoryThresholds) GetOutOfMemoryExceptionsNumberOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.OutOfMemoryExceptionsNumber, true
}

// SetOutOfMemoryExceptionsNumber sets field value
func (o *OutOfMemoryThresholds) SetOutOfMemoryExceptionsNumber(v int32) {
	o.OutOfMemoryExceptionsNumber = v
}

func (o OutOfMemoryThresholds) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["outOfMemoryExceptionsNumber"] = o.OutOfMemoryExceptionsNumber
	}
	return json.Marshal(toSerialize)
}

type NullableOutOfMemoryThresholds struct {
	value *OutOfMemoryThresholds
	isSet bool
}

func (v NullableOutOfMemoryThresholds) Get() *OutOfMemoryThresholds {
	return v.value
}

func (v *NullableOutOfMemoryThresholds) Set(val *OutOfMemoryThresholds) {
	v.value = val
	v.isSet = true
}

func (v NullableOutOfMemoryThresholds) IsSet() bool {
	return v.isSet
}

func (v *NullableOutOfMemoryThresholds) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutOfMemoryThresholds(val *OutOfMemoryThresholds) *NullableOutOfMemoryThresholds {
	return &NullableOutOfMemoryThresholds{value: val, isSet: true}
}

func (v NullableOutOfMemoryThresholds) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutOfMemoryThresholds) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


